<?php
return array (
  'cron_entry.EWRcarta_cleanUpDaily' => 'XenCarta: Daily Clean Up',
  'cron_entry.activitySummaryEmail' => 'Send activity summary email',
  'cron_entry.bdApi_cleanUpExpired' => '[bd] API: Clean Up Expired Data',
  'cron_entry.cleanUpDaily' => 'Daily clean up',
  'cron_entry.cleanUpHourly' => 'Hourly clean up',
  'cron_entry.dailyStats' => 'Record daily statistics',
  'cron_entry.deleteExpiredBans' => 'Delete expired bans',
  'cron_entry.downgradeExpired' => 'Downgrade expired user upgrades',
  'cron_entry.emailBounce' => 'Process email bounces',
  'cron_entry.emailUnsubscribe' => 'Process email unsubscribe requests',
  'cron_entry.expireTempUserChanges' => 'Expire temporary user changes',
  'cron_entry.feeder' => 'Feeder',
  'cron_entry.fileCheck' => 'Perform file health check',
  'cron_entry.forumStatistics' => 'Rebuild forum statistics',
  'cron_entry.memberStatsCache' => 'Rebuild member stats cache',
  'cron_entry.rebuildSearchForumCache' => 'Rebuild expired search forum caches',
  'cron_entry.run_successfully' => 'Cron entry was run successfully.',
  'cron_entry.sitemap' => 'Rebuild sitemap',
  'cron_entry.th_updateCheck_uix' => '[TH] UI.X: Check for updates',
  'cron_entry.thmonetize_cleanUpDaily' => '[TH] Monetize: Daily clean up',
  'cron_entry.thmonetize_communication' => '[TH] Monetize: Send communication',
  'cron_entry.trophy' => 'Update user trophies',
  'cron_entry.userGroupPromotions' => 'User group promotions',
  'cron_entry.views' => 'Update view counters',
  'cron_entry.warningExpiry' => 'Handle expired warnings',
);