<?php
// FROM HASH: 79e46b24b1f71e72af1120507b631182
return array(
'code' => function($__templater, array $__vars, $__extensions = null)
{
	$__finalCompiled = '';
	if ($__templater->method($__vars['email'], 'isInsert', array())) {
		$__finalCompiled .= '
	';
		$__templater->pageParams['pageTitle'] = $__templater->preEscaped('Add email');
		$__finalCompiled .= '
';
	} else {
		$__finalCompiled .= '
	';
		$__templater->pageParams['pageTitle'] = $__templater->preEscaped('Edit email' . $__vars['xf']['language']['label_separator'] . ' ' . $__templater->escape($__vars['email']['title']));
		$__finalCompiled .= '
';
	}
	$__finalCompiled .= '

';
	if ($__templater->method($__vars['email'], 'isUpdate', array())) {
		$__templater->pageParams['pageAction'] = $__templater->preEscaped('
	' . $__templater->button('', array(
			'href' => $__templater->func('link', array('monetize-emails/delete', $__vars['email'], ), false),
			'icon' => 'delete',
			'overlay' => 'true',
		), '', array(
		)) . '
');
	}
	$__finalCompiled .= '

' . $__templater->form('
	<div class="block-container">
		<h2 class="block-tabHeader tabs hScroller" data-xf-init="tabs h-scroller" role="tablist">
			<span class="hScroller-scroll">
				<a class="tabs-tab is-active" role="tab" tabindex="0" aria-controls="general-options">' . 'General options' . '</a>
				' . $__templater->callMacro('thmonetize_helper_criteria', 'user_upgrade_tabs', array(), $__vars) . '
				' . $__templater->callMacro('helper_criteria', 'user_tabs', array(), $__vars) . '
			</span>
		</h2>

		<ul class="tabPanes block-body">
			<li class="is-active" role="tabpanel" id="general-options">
				
				' . $__templater->callMacro('thmonetize_communication_edit_macros', 'time', array(
		'sendRules' => $__vars['email']['send_rules'],
	), $__vars) . '

				<hr class="formRowSep" />

				' . $__templater->formRow('
					<div class="inputGroup inputGroup--numbers">
						' . $__templater->formNumberBox(array(
		'name' => 'limit_emails',
		'value' => $__vars['email']['limit_emails'],
		'placeholder' => 'Emails',
		'min' => '0',
	)) . '
						<span class="inputGroup-text">' . 'per' . '</span>
						' . $__templater->formNumberBox(array(
		'name' => 'limit_days',
		'value' => $__vars['email']['limit_days'],
		'placeholder' => 'Days',
		'min' => '0',
		'max' => ($__vars['xf']['options']['thmonetize_emailLogLength'] ?: ''),
	)) . '
						<span class="inputGroup-text">' . 'Days' . '</span>
					</div>
				', array(
		'rowtype' => 'input',
		'label' => 'Per user limit',
		'explain' => 'This controls the maximum number of this email that can be sent to a user during a specified period. The length of the period should not exceed the log retention period or the global/total emails per user limit. Set to 0 to allow unlimited emails.',
	)) . '

				<hr class="formRowSep" />

				' . $__templater->formTextBoxRow(array(
		'name' => 'from_name',
		'value' => (($__vars['email']['from_name'] ?: $__vars['xf']['options']['emailSenderName']) ?: $__vars['xf']['options']['boardTitle']),
	), array(
		'label' => 'From name',
	)) . '

				' . $__templater->formTextBoxRow(array(
		'name' => 'from_email',
		'value' => ($__vars['email']['from_email'] ?: $__vars['xf']['options']['defaultEmailAddress']),
		'type' => 'email',
	), array(
		'label' => 'From email',
	)) . '

				<hr class="formRowSep" />

				' . $__templater->formTextBoxRow(array(
		'name' => 'title',
		'value' => $__vars['email']['title'],
		'maxlength' => $__templater->func('max_length', array($__vars['email'], 'title', ), false),
		'required' => 'true',
	), array(
		'label' => 'Email title',
	)) . '

				' . $__templater->formRadioRow(array(
		'name' => 'format',
		'value' => $__vars['email']['format'],
	), array(array(
		'value' => '',
		'label' => 'Plain text',
		'_type' => 'option',
	),
	array(
		'value' => 'html',
		'label' => 'HTML',
		'hint' => 'Note that email clients handle HTML in widely varying ways. Be sure to test before sending HTML emails. A text version of your email will be generated by removing all HTML tags.',
		'_type' => 'option',
	)), array(
		'label' => 'Email format',
	)) . '

				' . $__templater->formCodeEditorRow(array(
		'name' => 'body',
		'value' => $__vars['email']['body'],
		'mode' => 'html',
		'data-line-wrapping' => 'true',
		'class' => 'codeEditor--autoSize codeEditor--proportional',
	), array(
		'label' => 'Email body',
		'explain' => ' ' . 'following_placeholders_will_be_replaced_in_email_for_email' . ' ' . 'You may also use {phrase:phrase_title} which will be replaced with the phrase text in the recipient\'s language.',
	)) . '

				' . $__templater->formCheckBoxRow(array(
	), array(array(
		'name' => 'active',
		'selected' => $__vars['email']['active'],
		'label' => 'Active',
		'_type' => 'option',
	),
	array(
		'name' => 'wrapped',
		'selected' => $__vars['email']['wrapped'],
		'label' => 'Include default email wrapper',
		'hint' => 'If selected, your email content will be wrapped in the standard header and footer used in emails sent elsewhere in XenForo.',
		'_type' => 'option',
	),
	array(
		'name' => 'unsub',
		'selected' => $__vars['email']['unsub'],
		'label' => 'Automatically include an unsubscribe link',
		'hint' => 'If selected, this email will automatically have an unsubscribe line added at the bottom. If you use the \'unsub\' token in the body, this option will be ignored.',
		'_type' => 'option',
	),
	array(
		'name' => 'receive_admin_email_only',
		'selected' => $__vars['email']['receive_admin_email_only'],
		'label' => '
						' . 'Only send to users opting to receive news and update emails' . '
					',
		'_type' => 'option',
	)), array(
		'label' => 'Options',
	)) . '
			</li>

			' . $__templater->callMacro('thmonetize_helper_criteria', 'user_upgrade_panes', array(
		'criteria' => $__templater->method($__vars['userUpgradeCriteria'], 'getCriteriaForTemplate', array()),
		'data' => $__templater->method($__vars['userUpgradeCriteria'], 'getExtraTemplateData', array()),
	), $__vars) . '

			' . $__templater->callMacro('helper_criteria', 'user_panes', array(
		'criteria' => $__templater->method($__vars['userCriteria'], 'getCriteriaForTemplate', array()),
		'data' => $__templater->method($__vars['userCriteria'], 'getExtraTemplateData', array()),
	), $__vars) . '
		</ul>

		' . $__templater->formSubmitRow(array(
		'sticky' => 'true',
		'icon' => 'save',
	), array(
	)) . '
	</div>
', array(
		'action' => $__templater->func('link', array('monetize-emails/save', $__vars['email'], ), false),
		'ajax' => 'true',
		'class' => 'block',
	));
	return $__finalCompiled;
}
);